# Build stage
FROM node:20 AS build
WORKDIR /TaskList/task-list-frontend

COPY package*.json ./
RUN npm install
COPY . .
RUN npx ng build --configuration production

# Serve stage com nginx
FROM nginx:alpine
COPY --from=build /TaskList/task-list-frontend/dist/task-list-app/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
